name: Compliance build

on:
    push:
        branches: [master]
        paths:
            - src/**/*.ts
            - .github/workflows/*.yaml

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Setup node
              uses: actions/setup-node@v4
              with:
                  node-version: '18'
            - name: Install packages
              run: npm install
            - name: Validate with eslint
              run: npm run lint
            - name: Build application
              run: npm run build
            - name: Build docs
              run: npm run docs
